### PR TITLE
Added arabic and getter for default anguage

### PR DESCRIPTION
**Pull request by MC0M**
Small addon. Added Arabic, and getter for default language.

### CODE REVIEW

**Comment by rmtheis** [comment]
I really like the change to add Arabic--if you were to make that change a separate PR I'd want to merge that right away.

For `DEFAULT`, I'm leaning against merging that change because it's not clear to me that it's helpful for developers. As a developer, you'd still need to set a string for that value.

**Comment by MC0M** [comment]
You do not. All you have to do is set it. Ex: Translate.DEFAULT_LANG = Locale.getDefault().getLanguage();

Now Language.DEFAULT_LANG is set to the Default Language (it reads the info from Translate.DEFAULT_LANG)

**Comment by MC0M** [comment]
The developer sets the string by adding Translate.DEFAULT_LANG = Locale.getDefault().getLanguage(); to the beginning of the activity. That stays the same until the user leaves the app.

**Comment by rmtheis** [comment]
Ah, I see. That sounds good! Thanks for the contribution and please feel free to propose any further changes!

**Pull request merged**
